server:
  port: 8081

spring:
  application:
    name: fraud-check
  datasource:
    username: appadmin
    password: password
    url: jdbc:postgresql://localhost:5432/fraudcheck
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true
