server:
  port: 8081

spring:
  application:
    name: fraud-check
  datasource:
    username: appadmin
    password: password
    url: jdbc:postgresql://localhost:5432/fraudcheck
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
